nelmio_api_doc:
    documentation:
        host: '%env(BASE_URL)%'
        info:
            title: Payments API
            description: This is a simple payments API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
