version: "2"
services:
  php:
    container_name: php
    build: ./docker/php-fpm
    entrypoint: ["/usr/local/bin/dockerize", "-wait", "tcp://mysql:3306", "-timeout", "20s"]
    command: ["/usr/sbin/php-fpm7", "--nodaemonize"]
    volumes:
      - .:/home/nonroot/payments_api
    env_file:
      - ./docker/.env
    links:
      - mysql
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes_from:
      - php
    env_file:
      - ./docker/.env
    links:
      - php
  mysql:
    container_name: mysql
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    env_file:
      - ./docker/.env
#      - ./.env
    ports:
      - "3308:3306"